using MySqlPunk.Core.Models;
using Npgsql;

namespace MySqlPunk.Core.Providers;

internal sealed partial class PostgreSqlDatabaseSession
{
    public override async Task<TableStructureInfo> GetTableStructureAsync(
        string database,
        DatabaseObjectInfo table,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(table);
        var schema = string.IsNullOrWhiteSpace(table.Schema) ? "public" : table.Schema;
        await using var connection = (NpgsqlConnection)await CreateConnectionAsync(database, cancellationToken).ConfigureAwait(false);
        await connection.OpenAsync(cancellationToken).ConfigureAwait(false);

        var columns = new List<StructureColumnInfo>();
        await using (var command = connection.CreateCommand())
        {
            command.CommandText = """
                SELECT a.attname,
                       pg_catalog.format_type(a.atttypid, a.atttypmod),
                       NOT a.attnotnull,
                       EXISTS (SELECT 1 FROM pg_catalog.pg_index i
                               WHERE i.indrelid = a.attrelid AND i.indisprimary AND a.attnum = ANY (i.indkey)),
                       pg_catalog.pg_get_expr(d.adbin, d.adrelid),
                       CASE WHEN a.attidentity = 'a' THEN 'GENERATED ALWAYS AS IDENTITY'
                            WHEN a.attidentity = 'd' THEN 'GENERATED BY DEFAULT AS IDENTITY'
                            WHEN a.attgenerated = 's' THEN 'GENERATED ALWAYS AS (' || pg_catalog.pg_get_expr(d.adbin, d.adrelid) || ') STORED'
                            ELSE '' END,
                       CASE WHEN a.attcollation <> 0 AND a.attcollation <> t.typcollation THEN coll.collname ELSE '' END,
                       COALESCE(pg_catalog.col_description(a.attrelid, a.attnum), '')
                FROM pg_catalog.pg_attribute a
                JOIN pg_catalog.pg_class c ON c.oid = a.attrelid
                JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
                JOIN pg_catalog.pg_type t ON t.oid = a.atttypid
                LEFT JOIN pg_catalog.pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
                LEFT JOIN pg_catalog.pg_collation coll ON coll.oid = a.attcollation
                WHERE n.nspname = @schema AND c.relname = @table
                  AND a.attnum > 0 AND NOT a.attisdropped
                ORDER BY a.attnum
                """;
            command.Parameters.AddWithValue("@schema", schema);
            command.Parameters.AddWithValue("@table", table.Name);
            await using var reader = await command.ExecuteReaderAsync(cancellationToken).ConfigureAwait(false);
            while (await reader.ReadAsync(cancellationToken).ConfigureAwait(false))
            {
                var extra = ReadText(reader, 5);
                columns.Add(new StructureColumnInfo(
                    columns.Count,
                    reader.GetString(0),
                    ReadText(reader, 1),
                    ReadFlag(reader, 2),
                    ReadFlag(reader, 3),
                    extra.StartsWith("GENERATED ALWAYS AS (", StringComparison.Ordinal) ? string.Empty : ReadText(reader, 4),
                    extra,
                    ReadText(reader, 6),
                    ReadText(reader, 7)));
            }
        }

        string comment;
        string definition;
        await using (var command = connection.CreateCommand())
        {
            command.CommandText = """
                SELECT COALESCE(pg_catalog.obj_description(c.oid, 'pg_class'), ''),
                       CASE WHEN c.relkind IN ('v', 'm') THEN pg_catalog.pg_get_viewdef(c.oid, true) ELSE '' END
                FROM pg_catalog.pg_class c
                JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
                WHERE n.nspname = @schema AND c.relname = @table
                """;
            command.Parameters.AddWithValue("@schema", schema);
            command.Parameters.AddWithValue("@table", table.Name);
            await using var reader = await command.ExecuteReaderAsync(cancellationToken).ConfigureAwait(false);
            if (await reader.ReadAsync(cancellationToken).ConfigureAwait(false))
            {
                comment = ReadText(reader, 0);
                definition = ReadText(reader, 1);
            }
            else
            {
                comment = string.Empty;
                definition = string.Empty;
            }
        }

        var indexes = new List<StructureIndexInfo>();
        if (table.Kind == DatabaseObjectKind.Table)
        {
            await using var command = connection.CreateCommand();
            command.CommandText = """
                SELECT i.relname,
                       ix.indisunique,
                       ix.indisprimary,
                       am.amname,
                       ARRAY(SELECT pg_catalog.pg_get_indexdef(ix.indexrelid, k.ord::int, true)
                                    || CASE WHEN k.ord <= ix.indnkeyatts AND (ix.indoption[k.ord - 1] & 1) = 1 THEN ' DESC' ELSE '' END
                                    || CASE WHEN k.ord > ix.indnkeyatts THEN ' (INCLUDE)' ELSE '' END
                             FROM pg_catalog.generate_series(1, ix.indnatts) AS k(ord)
                             ORDER BY k.ord),
                       pg_catalog.pg_get_indexdef(ix.indexrelid)
                FROM pg_catalog.pg_index ix
                JOIN pg_catalog.pg_class i ON i.oid = ix.indexrelid
                JOIN pg_catalog.pg_class t ON t.oid = ix.indrelid
                JOIN pg_catalog.pg_namespace n ON n.oid = t.relnamespace
                JOIN pg_catalog.pg_am am ON am.oid = i.relam
                WHERE n.nspname = @schema AND t.relname = @table
                ORDER BY ix.indisprimary DESC, i.relname
                """;
            command.Parameters.AddWithValue("@schema", schema);
            command.Parameters.AddWithValue("@table", table.Name);
            await using var reader = await command.ExecuteReaderAsync(cancellationToken).ConfigureAwait(false);
            while (await reader.ReadAsync(cancellationToken).ConfigureAwait(false))
            {
                var indexColumns = reader.IsDBNull(4)
                    ? Array.Empty<string>()
                    : reader.GetFieldValue<string[]>(4);
                indexes.Add(new StructureIndexInfo(
                    reader.GetString(0),
                    ReadFlag(reader, 1),
                    ReadFlag(reader, 2),
                    ReadText(reader, 3),
                    indexColumns,
                    ReadText(reader, 5)));
            }
        }

        var foreignKeys = new List<StructureForeignKeyInfo>();
        if (table.Kind == DatabaseObjectKind.Table)
        {
            await using var command = connection.CreateCommand();
            command.CommandText = """
                SELECT con.conname,
                       ARRAY(SELECT a.attname FROM pg_catalog.unnest(con.conkey) WITH ORDINALITY AS k(attnum, ord)
                             JOIN pg_catalog.pg_attribute a ON a.attrelid = con.conrelid AND a.attnum = k.attnum
                             ORDER BY k.ord),
                       nf.nspname,
                       cf.relname,
                       ARRAY(SELECT a.attname FROM pg_catalog.unnest(con.confkey) WITH ORDINALITY AS k(attnum, ord)
                             JOIN pg_catalog.pg_attribute a ON a.attrelid = con.confrelid AND a.attnum = k.attnum
                             ORDER BY k.ord),
                       con.confupdtype,
                       con.confdeltype
                FROM pg_catalog.pg_constraint con
                JOIN pg_catalog.pg_class c ON c.oid = con.conrelid
                JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
                JOIN pg_catalog.pg_class cf ON cf.oid = con.confrelid
                JOIN pg_catalog.pg_namespace nf ON nf.oid = cf.relnamespace
                WHERE con.contype = 'f' AND n.nspname = @schema AND c.relname = @table
                ORDER BY con.conname
                """;
            command.Parameters.AddWithValue("@schema", schema);
            command.Parameters.AddWithValue("@table", table.Name);
            await using var reader = await command.ExecuteReaderAsync(cancellationToken).ConfigureAwait(false);
            while (await reader.ReadAsync(cancellationToken).ConfigureAwait(false))
            {
                var referencedSchema = reader.GetString(2);
                var referencedTable = referencedSchema.Equals(schema, StringComparison.Ordinal)
                    ? reader.GetString(3)
                    : $"{referencedSchema}.{reader.GetString(3)}";
                foreignKeys.Add(new StructureForeignKeyInfo(
                    reader.GetString(0),
                    reader.GetFieldValue<string[]>(1),
                    referencedTable,
                    reader.GetFieldValue<string[]>(4),
                    DescribeAction(reader.GetChar(5)),
                    DescribeAction(reader.GetChar(6))));
            }
        }

        return new TableStructureInfo(table, columns, indexes, foreignKeys, comment, definition);
    }

    private static string DescribeAction(char action) => action switch
    {
        'a' => "NO ACTION",
        'r' => "RESTRICT",
        'c' => "CASCADE",
        'n' => "SET NULL",
        'd' => "SET DEFAULT",
        _ => action.ToString()
    };
}
