<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>MySqlPunk.Desktop</RootNamespace>
    <AssemblyName>mySQLPunk</AssemblyName>
    <ApplicationIcon>../mySQLPunk/punky.ico</ApplicationIcon>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
    <NoWarn>$(NoWarn);CS9057</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.1" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="12.1.1" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../mySQLPunk.Core/mySQLPunk.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="../mySQLPunk/punky.ico" Link="Assets/punky.ico" />
  </ItemGroup>

</Project>
